config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :sessions => 'users/sessions'
  }

  resources :articles
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  attachment :image
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  # delegate :name, to: :profile
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user!
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if user_signed_in? && @article.user_id = current_user.id
    @article.save
      redirect_to @article, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: '更新できました'
    else
      render :edit, alert: '更新できませんでした'
    end
  end

  def destroy
    if user_signed_in? && @article.destroy
      redirect_to root_path, notice: '削除に成功しました'
    else
      redirect_to root_path, alert: '削除できませんでした'
    end
  end

  private
  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :image)
  end

  def validate_user
    if @article.user != current_user
      redirect_to root_path, alert: '自分の投稿ではありません'
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    # Userが無事に作られたら、Profileを作成。
    if resource
      #resource == user
      profile = Profile.new
      profile.user_id = resource.id
      profile.name = params[:profile][:name]
      profile.save
    end
    # puts "========#{params[:profile][:name]}=========="
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for article do |f| %>
  <div id="cover-image" class="form-group padding-top-15 relative">
    <%# <%= image_tag 'gray-bg.jpg', class: 'article-image'%>
    <%# <i class="fa fa-camera"></i> %>
  </div>

  <%# 画像添付用Form %>
    <%= f.attachment_field :image %>

  <div class="form-group padding-top-15">
    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
  
  <div class="form-group">
    <%= f.label :title, '本文' %>
    <%= f.text_area :body, rows: 10, class: 'form-control' %>
  </div>
  
  <%= f.submit class: 'btn btn-success'%>

<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <div class="col-md-12 margin-top-5per article-block">
    <h1 class="text-center">投稿の編集</h1>
    <%# <%= image_tag 'cat.jpg', class:'article-image padding-top-15'%>
    <div class="padding-bottom-15">
      <%= render 'form', article: @article, style: 'margin-bottom: 10px'%>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
  <% @articles.each do |article| %>
    <%= link_to article do %>
      <div class="col-md-3 margin-top-5per article-block">
      <% if article.image_id.present? %>
        <%= image_tag attachment_url(article, :image), class:'img-responsive padding-top-15 article-list-image'%>
        <% else %>
        <%= image_tag 'person.jpg', class:'img-responsive padding-top-15 article-list-image' %>
        <% end %>
        <div class="padding-bottom-15">
          <p class="title"><%= article.title %></p>
          <span><%= article.created_at.strftime("%Y年%m月%d日") %></span>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
  <div class="row">
    <% if user_signed_in? %>
    <%= link_to '新規作成', new_article_path, class: 'margin-top-5per btn btn-primary', style: 'margin-bottom: 10px'%>
    <% else %>
      <%= link_to '新規作成', new_user_registration_path, class: 'margin-top-5per btn btn-primary', style: 'margin-bottom: 10px'%>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="col-md-12 margin-top-5per article-block">
    <h1 class="text-center">新規作成</h1>
    <%# <%= image_tag 'cat.jpg', class:'article-image padding-top-15'%>
    <div class="padding-bottom-15">
      <%= render 'form', article: @article %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="col-md-12 margin-top-5per article-block">
    
    <% if @article.image_id.present? %>
    <%= image_tag attachment_url(@article, :image), class: 'article-image padding-top-15' %>
    <% end %>

    <h1><%= @article.title %></h1>
    <div class="padding-bottom-15" style="padding: 10px">
      <%= simple_format @article.body %>
      <p class="text-right"><%= @article.created_at.strftime("%Y年%m月%d日") %></p>
    </div>
    <%= link_to '編集', edit_article_path(@article), class: 'btn btn-primary', style: 'margin-bottom: 10px; margin-right: 10px' %>
    <%= link_to '削除', article_path(@article), method: :delete, data: {confirm: '削除してもよろしいですか？'}, class: 'btn btn-danger', style: 'margin-bottom: 10px'%>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <% if user_signed_in? %>
          <a class="navbar-brand" href="/">うちなーウォーカー @<%= current_user.profile.name %></a>
      <% else %>
        <a class="navbar-brand" href="/">うちなーウォーカー</a>
        <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navigation">
      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
        <%= link_to '新規作成', new_article_path %>
          &nbsp;
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete%>
        <% else %>
          <%= link_to 'ユーザ登録', new_user_registration_path %>
          &nbsp;
          <%= link_to 'ログイン', new_user_session_path %>
        <% end %>
          </p>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>うちなーウォーカー</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render '/layouts/header' %>

<!--  新規登録やログイン時にメッセージを表示-->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
  </body>
</html>